export const bookAbbreviations = {
	Ps: 'Psalmul',
	Is: 'Isaia',
	Evr: 'Evrei',
	Ier: 'Ieremia',
	Zah: 'Zaharia',
	Fapte: 'Faptele Apostolilor',
	Col: 'Coloseni',
	Apoc: 'Apocalipsa',
	Cor: 'Corinteni',
	Prov: 'Proverbe',
	Pet: 'Petru',
	Deut: 'Deuteronomul',
	Ecl: 'Eclesiastul',
	Iac: 'Iacov',
	Efes: 'Efeseni',
	Mal: 'Maleahi',
	Mat: 'Matei',
	Lev: 'Leviticul',
	Tim: 'Timotei',
}
