/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ReadBookChapterRouteImport } from './routes/read.$book.$chapter'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReadBookChapterRoute = ReadBookChapterRouteImport.update({
  id: '/read/$book/$chapter',
  path: '/read/$book/$chapter',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/read/$book/$chapter': typeof ReadBookChapterRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/read/$book/$chapter': typeof ReadBookChapterRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/read/$book/$chapter': typeof ReadBookChapterRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/read/$book/$chapter'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/read/$book/$chapter'
  id: '__root__' | '/' | '/read/$book/$chapter'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ReadBookChapterRoute: typeof ReadBookChapterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/read/$book/$chapter': {
      id: '/read/$book/$chapter'
      path: '/read/$book/$chapter'
      fullPath: '/read/$book/$chapter'
      preLoaderRoute: typeof ReadBookChapterRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ReadBookChapterRoute: ReadBookChapterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
