/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ShellRouteImport } from './routes/shell'
import { Route as Char123LocaleChar125RouteRouteImport } from './routes/{-$locale}/route'
import { Route as Char123LocaleChar125IndexRouteImport } from './routes/{-$locale}/index'
import { Route as Char123LocaleChar125ReadRouteImport } from './routes/{-$locale}/read'
import { Route as Char123LocaleChar125ReadBookChapterRouteImport } from './routes/{-$locale}/read.$book.$chapter'

const ShellRoute = ShellRouteImport.update({
  id: '/shell',
  path: '/shell',
  getParentRoute: () => rootRouteImport,
} as any)
const Char123LocaleChar125RouteRoute =
  Char123LocaleChar125RouteRouteImport.update({
    id: '/{-$locale}',
    path: '/{-$locale}',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char123LocaleChar125IndexRoute =
  Char123LocaleChar125IndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => Char123LocaleChar125RouteRoute,
  } as any)
const Char123LocaleChar125ReadRoute =
  Char123LocaleChar125ReadRouteImport.update({
    id: '/read',
    path: '/read',
    getParentRoute: () => Char123LocaleChar125RouteRoute,
  } as any)
const Char123LocaleChar125ReadBookChapterRoute =
  Char123LocaleChar125ReadBookChapterRouteImport.update({
    id: '/$book/$chapter',
    path: '/$book/$chapter',
    getParentRoute: () => Char123LocaleChar125ReadRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/{-$locale}': typeof Char123LocaleChar125RouteRouteWithChildren
  '/shell': typeof ShellRoute
  '/{-$locale}/read': typeof Char123LocaleChar125ReadRouteWithChildren
  '/{-$locale}/': typeof Char123LocaleChar125IndexRoute
  '/{-$locale}/read/$book/$chapter': typeof Char123LocaleChar125ReadBookChapterRoute
}
export interface FileRoutesByTo {
  '/shell': typeof ShellRoute
  '/{-$locale}/read': typeof Char123LocaleChar125ReadRouteWithChildren
  '/{-$locale}': typeof Char123LocaleChar125IndexRoute
  '/{-$locale}/read/$book/$chapter': typeof Char123LocaleChar125ReadBookChapterRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/{-$locale}': typeof Char123LocaleChar125RouteRouteWithChildren
  '/shell': typeof ShellRoute
  '/{-$locale}/read': typeof Char123LocaleChar125ReadRouteWithChildren
  '/{-$locale}/': typeof Char123LocaleChar125IndexRoute
  '/{-$locale}/read/$book/$chapter': typeof Char123LocaleChar125ReadBookChapterRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/{-$locale}'
    | '/shell'
    | '/{-$locale}/read'
    | '/{-$locale}/'
    | '/{-$locale}/read/$book/$chapter'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/shell'
    | '/{-$locale}/read'
    | '/{-$locale}'
    | '/{-$locale}/read/$book/$chapter'
  id:
    | '__root__'
    | '/{-$locale}'
    | '/shell'
    | '/{-$locale}/read'
    | '/{-$locale}/'
    | '/{-$locale}/read/$book/$chapter'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  Char123LocaleChar125RouteRoute: typeof Char123LocaleChar125RouteRouteWithChildren
  ShellRoute: typeof ShellRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/shell': {
      id: '/shell'
      path: '/shell'
      fullPath: '/shell'
      preLoaderRoute: typeof ShellRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/{-$locale}': {
      id: '/{-$locale}'
      path: '/{-$locale}'
      fullPath: '/{-$locale}'
      preLoaderRoute: typeof Char123LocaleChar125RouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/{-$locale}/': {
      id: '/{-$locale}/'
      path: '/'
      fullPath: '/{-$locale}/'
      preLoaderRoute: typeof Char123LocaleChar125IndexRouteImport
      parentRoute: typeof Char123LocaleChar125RouteRoute
    }
    '/{-$locale}/read': {
      id: '/{-$locale}/read'
      path: '/read'
      fullPath: '/{-$locale}/read'
      preLoaderRoute: typeof Char123LocaleChar125ReadRouteImport
      parentRoute: typeof Char123LocaleChar125RouteRoute
    }
    '/{-$locale}/read/$book/$chapter': {
      id: '/{-$locale}/read/$book/$chapter'
      path: '/$book/$chapter'
      fullPath: '/{-$locale}/read/$book/$chapter'
      preLoaderRoute: typeof Char123LocaleChar125ReadBookChapterRouteImport
      parentRoute: typeof Char123LocaleChar125ReadRoute
    }
  }
}

interface Char123LocaleChar125ReadRouteChildren {
  Char123LocaleChar125ReadBookChapterRoute: typeof Char123LocaleChar125ReadBookChapterRoute
}

const Char123LocaleChar125ReadRouteChildren: Char123LocaleChar125ReadRouteChildren =
  {
    Char123LocaleChar125ReadBookChapterRoute:
      Char123LocaleChar125ReadBookChapterRoute,
  }

const Char123LocaleChar125ReadRouteWithChildren =
  Char123LocaleChar125ReadRoute._addFileChildren(
    Char123LocaleChar125ReadRouteChildren,
  )

interface Char123LocaleChar125RouteRouteChildren {
  Char123LocaleChar125ReadRoute: typeof Char123LocaleChar125ReadRouteWithChildren
  Char123LocaleChar125IndexRoute: typeof Char123LocaleChar125IndexRoute
}

const Char123LocaleChar125RouteRouteChildren: Char123LocaleChar125RouteRouteChildren =
  {
    Char123LocaleChar125ReadRoute: Char123LocaleChar125ReadRouteWithChildren,
    Char123LocaleChar125IndexRoute: Char123LocaleChar125IndexRoute,
  }

const Char123LocaleChar125RouteRouteWithChildren =
  Char123LocaleChar125RouteRoute._addFileChildren(
    Char123LocaleChar125RouteRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  Char123LocaleChar125RouteRoute: Char123LocaleChar125RouteRouteWithChildren,
  ShellRoute: ShellRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
